# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'photon-garage-door-opener' do
	pod "Spark-SDK"
end

target 'photon-garage-door-openerTests' do

end

